# Generated by Django 3.0.8 on 2020-07-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0002_correlation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='correlation',
        ),
    ]
